import {execFileSync} from "child_process";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";

const defaultBaseUrl = "https://hl7.org/fhir/6.0.0-ballot5/";
const inputNames = [
    "profiles-resources.json",
    "profiles-types.json",
    "profiles-others.json",
    "search-parameters.json",
] as const;
const outputNames = [
    "choiceTypePaths",
    "path2Repeating",
    "path2Type",
    "pathsDefinedElsewhere",
    "resourcesWithUrlParam",
    "type2Parent",
] as const;

function argumentValue(name: string): string | undefined {
    const index = process.argv.indexOf(name);
    return index >= 0 ? process.argv[index + 1] : undefined;
}

async function download(url: string, destination: string): Promise<void> {
    const response = await fetch(url, {
        headers: {"User-Agent": "fhirpath-lab-model-generator/1.0"},
        redirect: "follow",
    });
    if (!response.ok) {
        throw new Error(`GET ${url} -> HTTP ${response.status}`);
    }
    fs.writeFileSync(destination, Buffer.from(await response.arrayBuffer()));
}

async function main(): Promise<void> {
    const baseUrl = (argumentValue("--base-url") ?? defaultBaseUrl).replace(/\/?$/, "/");
    const outputDir = path.resolve(__dirname, "..", "..", "models", "r6");
    const temporaryDir = fs.mkdtempSync(path.join(os.tmpdir(), "fhirpath-r6-model-"));
    const extractedDir = path.join(temporaryDir, "extracted");
    fs.mkdirSync(extractedDir);

    try {
        for (const inputName of inputNames) {
            const url = new URL(inputName, baseUrl).toString();
            console.error(`[generate:fhirpath-r6] downloading ${url}`);
            await download(url, path.join(temporaryDir, inputName));
        }

        const extractor = require.resolve("fhirpath/fhir-context/extract-model-info.js");
        execFileSync(process.execPath, [
            extractor,
            "--fhirDefDir", temporaryDir,
            "--outputDir", extractedDir,
        ], {stdio: "inherit"});

        fs.mkdirSync(outputDir, {recursive: true});
        for (const outputName of outputNames) {
            const json = fs.readFileSync(path.join(extractedDir, `${outputName}.json`), "utf8");
            const content = [
                "// Generated by `npm run generate:fhirpath-r6`; do not edit manually.",
                `export const ${outputName} = ${json};`,
                "",
            ].join("\n");
            fs.writeFileSync(path.join(outputDir, `${outputName}.ts`), content, "utf8");
        }
        console.error(`[generate:fhirpath-r6] wrote ${outputNames.length} data files to ${outputDir}`);
    } finally {
        fs.rmSync(temporaryDir, {recursive: true, force: true});
    }
}

main().catch(error => {
    console.error(error instanceof Error ? error.stack : error);
    process.exitCode = 1;
});
