// Generated by `npm run generate:fhirpath-r6`; do not edit manually.
export const choiceTypePaths = {
  "ActivityDefinition.asNeeded": [
    "Boolean",
    "CodeableConcept"
  ],
  "ActivityDefinition.product": [
    "Reference",
    "CodeableConcept"
  ],
  "ActivityDefinition.subject": [
    "CodeableConcept",
    "Reference",
    "Canonical"
  ],
  "ActivityDefinition.timing": [
    "Timing",
    "Age",
    "Range",
    "Duration",
    "RelativeTime"
  ],
  "ActivityDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "ActorDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "AdministrableProductDefinition.property.value": [
    "CodeableConcept",
    "Quantity",
    "Range",
    "Date",
    "Boolean",
    "Markdown",
    "Attachment",
    "Reference"
  ],
  "AdverseEvent.effect": [
    "DateTime",
    "Period"
  ],
  "AdverseEvent.suspectEntity.occurrence": [
    "DateTime",
    "Period"
  ],
  "AllergyIntolerance.onset": [
    "DateTime",
    "Age",
    "Period",
    "Range",
    "String"
  ],
  "Annotation.author": [
    "Reference",
    "String"
  ],
  "ArtifactAssessment.artifact": [
    "Reference",
    "Canonical",
    "Uri"
  ],
  "ArtifactAssessment.relatesTo.target": [
    "Uri",
    "Attachment",
    "Canonical",
    "Reference",
    "Markdown"
  ],
  "AuditEvent.agent.network": [
    "Reference",
    "Uri",
    "String"
  ],
  "AuditEvent.entity.detail.value": [
    "Quantity",
    "CodeableConcept",
    "String",
    "Boolean",
    "Integer",
    "Range",
    "Ratio",
    "Time",
    "DateTime",
    "Period",
    "Base64Binary"
  ],
  "AuditEvent.occurred": [
    "Period",
    "DateTime"
  ],
  "BiologicallyDerivedProduct.collection.collected": [
    "DateTime",
    "Period"
  ],
  "BiologicallyDerivedProduct.property.value": [
    "Boolean",
    "Integer",
    "CodeableConcept",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "String",
    "Attachment"
  ],
  "CanonicalResource.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "CapabilityStatement.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "CareTeam.participant.effective": [
    "Period",
    "Timing"
  ],
  "Claim.accident.location": [
    "Address",
    "Reference"
  ],
  "Claim.event.when": [
    "DateTime",
    "Period"
  ],
  "Claim.item.location": [
    "CodeableConcept",
    "Address",
    "Reference"
  ],
  "Claim.item.serviced": [
    "Date",
    "Period"
  ],
  "Claim.supportingInfo.timing": [
    "DateTime",
    "Period",
    "Timing"
  ],
  "Claim.supportingInfo.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "ClaimResponse.addItem.location": [
    "CodeableConcept",
    "Address",
    "Reference"
  ],
  "ClaimResponse.addItem.serviced": [
    "Date",
    "Period"
  ],
  "ClaimResponse.event.when": [
    "DateTime",
    "Period"
  ],
  "ClaimResponse.supportingInfo.timing": [
    "DateTime",
    "Period",
    "Timing"
  ],
  "ClaimResponse.supportingInfo.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "ClinicalUseDefinition.indication.duration": [
    "Range",
    "String"
  ],
  "ClinicalUseDefinition.interaction.interactant.item": [
    "Reference",
    "CodeableConcept"
  ],
  "CodeSystem.concept.property.value": [
    "Code",
    "Coding",
    "String",
    "Integer",
    "Boolean",
    "DateTime",
    "Decimal"
  ],
  "CodeSystem.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "Communication.payload.content": [
    "Attachment",
    "Reference",
    "CodeableConcept",
    "String"
  ],
  "CommunicationRequest.occurrence": [
    "DateTime",
    "Period"
  ],
  "CommunicationRequest.payload.content": [
    "Attachment",
    "Reference",
    "CodeableConcept",
    "String"
  ],
  "CompartmentDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "Composition.relatesTo.target": [
    "Uri",
    "Attachment",
    "Canonical",
    "Reference",
    "Markdown"
  ],
  "ConceptMap.group.element.target.dependsOn.value": [
    "Code",
    "Coding",
    "String",
    "Boolean",
    "Quantity"
  ],
  "ConceptMap.group.element.target.property.value": [
    "Coding",
    "String",
    "Integer",
    "Boolean",
    "DateTime",
    "Decimal",
    "Code"
  ],
  "ConceptMap.sourceScope": [
    "Uri",
    "Canonical"
  ],
  "ConceptMap.targetScope": [
    "Uri",
    "Canonical"
  ],
  "ConceptMap.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "Condition.abatement": [
    "DateTime",
    "Age",
    "Period",
    "Range",
    "String"
  ],
  "Condition.onset": [
    "DateTime",
    "Age",
    "Period",
    "Range",
    "String"
  ],
  "Coverage.costToBeneficiary.value": [
    "Quantity",
    "Money"
  ],
  "CoverageEligibilityRequest.event.when": [
    "DateTime",
    "Period"
  ],
  "CoverageEligibilityRequest.serviced": [
    "Date",
    "Period"
  ],
  "CoverageEligibilityResponse.event.when": [
    "DateTime",
    "Period"
  ],
  "CoverageEligibilityResponse.insurance.item.benefit.allowed": [
    "UnsignedInt",
    "String",
    "Money"
  ],
  "CoverageEligibilityResponse.insurance.item.benefit.used": [
    "UnsignedInt",
    "String",
    "Money"
  ],
  "CoverageEligibilityResponse.serviced": [
    "Date",
    "Period"
  ],
  "DataRequirement.dateFilter.value": [
    "DateTime",
    "Period",
    "Duration"
  ],
  "DataRequirement.subject": [
    "CodeableConcept",
    "Reference"
  ],
  "DataRequirement.valueFilter.value": [
    "Boolean",
    "Integer",
    "String",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange"
  ],
  "DetectedIssue.identified": [
    "DateTime",
    "Period",
    "Timing"
  ],
  "Device.property.value": [
    "Quantity",
    "CodeableConcept",
    "String",
    "Boolean",
    "Integer",
    "Range",
    "Attachment"
  ],
  "DeviceDefinition.hasPart.definition": [
    "Canonical",
    "CodeableConcept"
  ],
  "DeviceDefinition.link.relatedDevice": [
    "Canonical",
    "CodeableConcept"
  ],
  "DeviceDefinition.property.value": [
    "Quantity",
    "CodeableConcept",
    "String",
    "Boolean",
    "Integer",
    "Range",
    "Attachment"
  ],
  "DeviceDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "DeviceRequest.occurrence": [
    "DateTime",
    "Period",
    "Timing"
  ],
  "DeviceRequest.parameter.value": [
    "CodeableConcept",
    "Quantity",
    "Range",
    "Boolean"
  ],
  "DeviceRequest.product": [
    "CodeableConcept",
    "Reference",
    "Canonical"
  ],
  "DiagnosticReport.effective": [
    "DateTime",
    "Period"
  ],
  "DocumentReference.content.profile.value": [
    "Coding",
    "Uri",
    "Canonical"
  ],
  "Dosage.doseAndRate.dose": [
    "Range",
    "Quantity",
    "Expression"
  ],
  "Dosage.doseAndRate.rate": [
    "Ratio",
    "Range",
    "Quantity",
    "Expression"
  ],
  "DosageCondition.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "DosageSafety.doseLimit.value": [
    "Integer",
    "Quantity",
    "Expression"
  ],
  "ElementDefinition.defaultValue": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "ElementDefinition.example.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "ElementDefinition.fixed": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "ElementDefinition.maxValue": [
    "Date",
    "DateTime",
    "Instant",
    "Time",
    "Decimal",
    "Integer",
    "Integer64",
    "PositiveInt",
    "UnsignedInt",
    "Quantity"
  ],
  "ElementDefinition.minValue": [
    "Date",
    "DateTime",
    "Instant",
    "Time",
    "Decimal",
    "Integer",
    "Integer64",
    "PositiveInt",
    "UnsignedInt",
    "Quantity"
  ],
  "ElementDefinition.pattern": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "EventDefinition.subject": [
    "CodeableConcept",
    "Reference"
  ],
  "EventDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "Evidence.relatesTo.target": [
    "Uri",
    "Attachment",
    "Canonical",
    "Reference",
    "Markdown"
  ],
  "Evidence.statistic.modelCharacteristic.value": [
    "Quantity",
    "Range",
    "CodeableConcept"
  ],
  "Evidence.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "EvidenceVariable.category.value": [
    "CodeableConcept",
    "Quantity",
    "Range",
    "Reference"
  ],
  "EvidenceVariable.definitionModifier.value": [
    "CodeableConcept",
    "Boolean",
    "Quantity",
    "Range",
    "Period",
    "RelativeTime",
    "Reference",
    "Expression",
    "Uri"
  ],
  "EvidenceVariable.relatesTo.target": [
    "Uri",
    "Attachment",
    "Canonical",
    "Reference",
    "Markdown"
  ],
  "EvidenceVariable.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "ExampleScenario.instance.structureProfile": [
    "Canonical",
    "Uri"
  ],
  "ExampleScenario.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "ExplanationOfBenefit.accident.location": [
    "Address",
    "Reference"
  ],
  "ExplanationOfBenefit.addItem.location": [
    "CodeableConcept",
    "Address",
    "Reference"
  ],
  "ExplanationOfBenefit.addItem.serviced": [
    "Date",
    "Period"
  ],
  "ExplanationOfBenefit.benefitBalance.financial.allowed": [
    "UnsignedInt",
    "String",
    "Money"
  ],
  "ExplanationOfBenefit.benefitBalance.financial.used": [
    "UnsignedInt",
    "Money"
  ],
  "ExplanationOfBenefit.event.when": [
    "DateTime",
    "Period"
  ],
  "ExplanationOfBenefit.item.location": [
    "CodeableConcept",
    "Address",
    "Reference"
  ],
  "ExplanationOfBenefit.item.serviced": [
    "Date",
    "Period"
  ],
  "ExplanationOfBenefit.supportingInfo.timing": [
    "DateTime",
    "Period",
    "Timing"
  ],
  "ExplanationOfBenefit.supportingInfo.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "Extension.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "FamilyMemberHistory.age": [
    "Age",
    "Range",
    "String"
  ],
  "FamilyMemberHistory.born": [
    "Period",
    "Date",
    "String"
  ],
  "FamilyMemberHistory.condition.onset": [
    "Age",
    "Range",
    "Period",
    "String"
  ],
  "FamilyMemberHistory.deceased": [
    "Boolean",
    "Age",
    "Range",
    "Date",
    "String"
  ],
  "FamilyMemberHistory.procedure.performed": [
    "Age",
    "Range",
    "Period",
    "String",
    "DateTime"
  ],
  "Goal.start": [
    "Date",
    "CodeableConcept"
  ],
  "Goal.target.detail": [
    "Quantity",
    "Range",
    "CodeableConcept",
    "String",
    "Boolean",
    "Integer",
    "Ratio"
  ],
  "Goal.target.due": [
    "Date",
    "Duration"
  ],
  "Group.characteristic.duration": [
    "Duration",
    "Range"
  ],
  "Group.characteristic.instances": [
    "UnsignedInt",
    "Range"
  ],
  "Group.characteristic.value": [
    "CodeableConcept",
    "Boolean",
    "Quantity",
    "Range",
    "Reference",
    "Uri",
    "Expression"
  ],
  "Group.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "GuidanceResponse.module": [
    "Uri",
    "Canonical",
    "CodeableConcept"
  ],
  "HealthcareService.eligibility.value": [
    "CodeableConcept",
    "Boolean",
    "Quantity",
    "Range",
    "Reference"
  ],
  "Immunization.occurrence": [
    "DateTime",
    "String"
  ],
  "ImplementationGuide.definition.page.source": [
    "Url",
    "String",
    "Markdown"
  ],
  "ImplementationGuide.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "Ingredient.substance.strength.concentration": [
    "Ratio",
    "RatioRange",
    "CodeableConcept",
    "Quantity"
  ],
  "Ingredient.substance.strength.presentation": [
    "Ratio",
    "RatioRange",
    "CodeableConcept",
    "Quantity"
  ],
  "Ingredient.substance.strength.referenceStrength.strength": [
    "Ratio",
    "RatioRange",
    "Quantity"
  ],
  "Library.subject": [
    "CodeableConcept",
    "Reference"
  ],
  "Library.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "ManufacturedItemDefinition.property.value": [
    "CodeableConcept",
    "Quantity",
    "Range",
    "Date",
    "Boolean",
    "Markdown",
    "Attachment",
    "Reference"
  ],
  "Measure.group.subject": [
    "CodeableConcept",
    "Reference"
  ],
  "Measure.subject": [
    "CodeableConcept",
    "Reference"
  ],
  "Measure.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "MeasureReport.group.measureScore": [
    "Quantity",
    "DateTime",
    "CodeableConcept",
    "Period",
    "Range",
    "Duration",
    "Boolean",
    "Ratio"
  ],
  "MeasureReport.group.stratifier.stratum.component.value": [
    "CodeableConcept",
    "Boolean",
    "Period",
    "Quantity",
    "Range",
    "Reference",
    "String"
  ],
  "MeasureReport.group.stratifier.stratum.measureScore": [
    "Quantity",
    "DateTime",
    "CodeableConcept",
    "Period",
    "Range",
    "Duration",
    "Boolean",
    "Ratio"
  ],
  "MeasureReport.group.stratifier.stratum.value": [
    "CodeableConcept",
    "Boolean",
    "Period",
    "Quantity",
    "Range",
    "Reference",
    "String"
  ],
  "Medication.ingredient.strength": [
    "Ratio",
    "CodeableConcept",
    "Quantity"
  ],
  "MedicationAdministration.dosage.rate": [
    "Ratio",
    "Quantity"
  ],
  "MedicationAdministration.occurrence": [
    "DateTime",
    "Period",
    "Timing"
  ],
  "MedicationRequest.effectiveTiming": [
    "Duration",
    "Range",
    "Period"
  ],
  "MedicationRequest.substitution.allowed": [
    "Boolean",
    "CodeableConcept"
  ],
  "MedicationStatement.effective": [
    "DateTime",
    "Period",
    "Timing"
  ],
  "MedicinalProductDefinition.characteristic.value": [
    "CodeableConcept",
    "Markdown",
    "Quantity",
    "Range",
    "Integer",
    "Date",
    "Boolean",
    "Attachment"
  ],
  "MessageDefinition.event": [
    "Coding",
    "Uri"
  ],
  "MessageDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "MessageHeader.destination.endpoint": [
    "Url",
    "Reference"
  ],
  "MessageHeader.event": [
    "Coding",
    "Uri",
    "Canonical"
  ],
  "MessageHeader.source.endpoint": [
    "Url",
    "Reference"
  ],
  "MetadataResource.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "NamingSystem.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "NutritionIntake.nutritionItem.consumedItem.rate": [
    "Quantity",
    "Ratio"
  ],
  "NutritionIntake.occurrence": [
    "DateTime",
    "Period"
  ],
  "NutritionIntake.reported": [
    "Boolean",
    "Reference"
  ],
  "NutritionOrder.enteralFormula.administration.rate": [
    "Quantity",
    "Ratio"
  ],
  "NutritionOrder.enteralFormula.deliveryDevice": [
    "CodeableConcept",
    "Canonical"
  ],
  "NutritionProduct.characteristic.value": [
    "CodeableConcept",
    "String",
    "Quantity",
    "Base64Binary",
    "Attachment",
    "Boolean"
  ],
  "NutritionProduct.ingredient.amount": [
    "Ratio",
    "Quantity"
  ],
  "NutritionProduct.nutrient.amount": [
    "Ratio",
    "Quantity"
  ],
  "Observation.component.value": [
    "Quantity",
    "CodeableConcept",
    "String",
    "Boolean",
    "Integer",
    "Range",
    "Ratio",
    "SampledData",
    "Time",
    "DateTime",
    "Period",
    "Attachment"
  ],
  "Observation.effective": [
    "DateTime",
    "Period",
    "Timing",
    "Instant"
  ],
  "Observation.value": [
    "Quantity",
    "CodeableConcept",
    "String",
    "Boolean",
    "Integer",
    "Range",
    "Ratio",
    "SampledData",
    "Time",
    "DateTime",
    "Period",
    "Attachment"
  ],
  "ObservationDefinition.device": [
    "Reference",
    "Canonical"
  ],
  "ObservationDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "OperationDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "PackagedProductDefinition.packaging.property.value": [
    "CodeableConcept",
    "Quantity",
    "Date",
    "Boolean",
    "Attachment"
  ],
  "Parameters.parameter.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "Patient.deceased": [
    "Boolean",
    "DateTime"
  ],
  "Patient.multipleBirth": [
    "Boolean",
    "Integer"
  ],
  "PaymentReconciliation.allocation.targetItem": [
    "String",
    "Identifier",
    "PositiveInt"
  ],
  "Person.deceased": [
    "Boolean",
    "DateTime"
  ],
  "PlanDefinition.action.definition": [
    "Canonical",
    "Uri"
  ],
  "PlanDefinition.action.relatedAction.offset": [
    "Duration",
    "Range"
  ],
  "PlanDefinition.action.subject": [
    "CodeableConcept",
    "Reference",
    "Canonical"
  ],
  "PlanDefinition.action.timing": [
    "Age",
    "Duration",
    "Range",
    "Timing",
    "RelativeTime"
  ],
  "PlanDefinition.asNeeded": [
    "Boolean",
    "CodeableConcept"
  ],
  "PlanDefinition.goal.target.detail": [
    "Quantity",
    "Range",
    "CodeableConcept",
    "String",
    "Boolean",
    "Integer",
    "Ratio"
  ],
  "PlanDefinition.subject": [
    "CodeableConcept",
    "Reference",
    "Canonical"
  ],
  "PlanDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "Practitioner.deceased": [
    "Boolean",
    "DateTime"
  ],
  "Procedure.occurrence": [
    "DateTime",
    "Period",
    "String",
    "Age",
    "Range",
    "Timing"
  ],
  "Procedure.reported": [
    "Boolean",
    "Reference"
  ],
  "ProductShelfLife.period": [
    "Duration",
    "String"
  ],
  "Provenance.occurred": [
    "Period",
    "DateTime"
  ],
  "Questionnaire.item.answerOption.value": [
    "Decimal",
    "Integer",
    "Date",
    "DateTime",
    "Time",
    "String",
    "Uri",
    "Coding",
    "Quantity",
    "Reference"
  ],
  "Questionnaire.item.enableWhen.answer": [
    "Boolean",
    "Decimal",
    "Integer",
    "Date",
    "DateTime",
    "Time",
    "String",
    "Coding",
    "Quantity",
    "Reference",
    "Uri",
    "Attachment"
  ],
  "Questionnaire.item.initial.value": [
    "Boolean",
    "Decimal",
    "Integer",
    "Date",
    "DateTime",
    "Time",
    "String",
    "Uri",
    "Attachment",
    "Coding",
    "Quantity",
    "Reference"
  ],
  "Questionnaire.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "QuestionnaireResponse.item.answer.value": [
    "Boolean",
    "Decimal",
    "Integer",
    "Date",
    "DateTime",
    "Time",
    "String",
    "Uri",
    "Attachment",
    "Coding",
    "Quantity",
    "Reference"
  ],
  "RegulatedAuthorization.case.date": [
    "Period",
    "DateTime"
  ],
  "RelativeTime.offset": [
    "Duration",
    "Range"
  ],
  "RequestOrchestration.action.definition": [
    "Canonical",
    "Uri"
  ],
  "RequestOrchestration.action.participant.actor": [
    "Canonical",
    "Reference"
  ],
  "RequestOrchestration.action.relatedAction.offset": [
    "Duration",
    "Range"
  ],
  "RequestOrchestration.action.timing": [
    "DateTime",
    "Age",
    "Period",
    "Duration",
    "Range",
    "Timing",
    "RelativeTime"
  ],
  "Requirements.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "ResearchStudy.relatesTo.target": [
    "Uri",
    "Attachment",
    "Canonical",
    "Reference",
    "Markdown"
  ],
  "RiskAssessment.occurrence": [
    "DateTime",
    "Period"
  ],
  "RiskAssessment.prediction.probability": [
    "Decimal",
    "Quantity",
    "Range"
  ],
  "RiskAssessment.prediction.when": [
    "Period",
    "Range"
  ],
  "SearchParameter.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "ServiceRequest.occurrence": [
    "DateTime",
    "Period",
    "Timing"
  ],
  "ServiceRequest.orderDetail.parameter.value": [
    "Quantity",
    "Ratio",
    "Range",
    "Boolean",
    "CodeableConcept",
    "String",
    "Period"
  ],
  "ServiceRequest.orderDetail.parameterFocus": [
    "CodeableConcept",
    "Reference",
    "Canonical"
  ],
  "ServiceRequest.patientInstruction.instruction": [
    "Markdown",
    "Reference"
  ],
  "ServiceRequest.quantity": [
    "Quantity",
    "Ratio",
    "Range"
  ],
  "Specimen.collection.collected": [
    "DateTime",
    "Period"
  ],
  "Specimen.collection.fastingStatus": [
    "CodeableConcept",
    "Duration"
  ],
  "Specimen.processing.time": [
    "DateTime",
    "Period",
    "Duration"
  ],
  "SpecimenDefinition.typeTested.container.device": [
    "CodeableConcept",
    "Canonical"
  ],
  "SpecimenDefinition.typeTested.container.minimumVolume": [
    "Quantity",
    "String"
  ],
  "SpecimenDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "StructureDefinition.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "SubscriptionTopic.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "SubstanceDefinition.moiety.amount": [
    "Quantity",
    "String"
  ],
  "SubstanceDefinition.property.value": [
    "CodeableConcept",
    "Quantity",
    "Range",
    "Date",
    "Boolean",
    "Attachment"
  ],
  "SubstanceDefinition.relationship.amount": [
    "Quantity",
    "Ratio",
    "RatioRange",
    "String",
    "Range"
  ],
  "SubstanceDefinition.relationship.substanceDefinition": [
    "Reference",
    "CodeableConcept"
  ],
  "Task.focus.value": [
    "Reference",
    "Canonical"
  ],
  "Task.input.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "Task.output.value": [
    "Base64Binary",
    "Boolean",
    "Canonical",
    "Code",
    "Date",
    "DateTime",
    "Decimal",
    "Id",
    "Instant",
    "Integer",
    "Integer64",
    "Markdown",
    "Oid",
    "PositiveInt",
    "String",
    "Time",
    "UnsignedInt",
    "Uri",
    "Url",
    "Uuid",
    "Address",
    "Age",
    "Annotation",
    "Attachment",
    "CodeableConcept",
    "CodeableReference",
    "Coding",
    "ContactPoint",
    "Count",
    "Distance",
    "Duration",
    "HumanName",
    "Identifier",
    "Money",
    "Period",
    "Quantity",
    "Range",
    "Ratio",
    "RatioRange",
    "Reference",
    "SampledData",
    "Signature",
    "Timing",
    "ContactDetail",
    "DataRequirement",
    "Expression",
    "ParameterDefinition",
    "RelatedArtifact",
    "TriggerDefinition",
    "UsageContext",
    "Availability",
    "ExtendedContactDetail",
    "VirtualServiceDetail",
    "Dosage",
    "Meta"
  ],
  "TerminologyCapabilities.codeSystem.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "TerminologyCapabilities.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "Timing.repeat.bounds": [
    "Duration",
    "Range",
    "Period"
  ],
  "TriggerDefinition.timing": [
    "Timing",
    "Date",
    "DateTime"
  ],
  "UsageContext.value": [
    "CodeableConcept",
    "Quantity",
    "Range",
    "Reference",
    "Canonical"
  ],
  "ValueSet.expansion.contains.property.subProperty.value": [
    "Code",
    "Coding",
    "String",
    "Integer",
    "Boolean",
    "DateTime",
    "Decimal"
  ],
  "ValueSet.expansion.contains.property.value": [
    "Code",
    "Coding",
    "String",
    "Integer",
    "Boolean",
    "DateTime",
    "Decimal"
  ],
  "ValueSet.expansion.parameter.value": [
    "String",
    "Boolean",
    "Integer",
    "Decimal",
    "Uri",
    "Code",
    "DateTime"
  ],
  "ValueSet.versionAlgorithm": [
    "String",
    "Coding"
  ],
  "VirtualServiceDetail.address": [
    "Url",
    "String",
    "ContactPoint",
    "ExtendedContactDetail"
  ]
};
