<template>
  <div>
    <template v-if="questionnaire">
      <v-btn style="position: absolute; right: 34px; z-index: 2; margin-top: 4px;" color="primary"
        title="Show the QuestionnaireResponse based on the data in the Aidbox renderer" @click="logResponse()">Show
        Response</v-btn>
      <aidbox-form-renderer
        style="width: 100%; height: 100%; display: block"
        :questionnaire="JSON.stringify(questionnaire)" :questionnaire-response="questionnaireResponseString"
        hide-footer="true" @change="handleChange" />
    </template>
    <template v-else>
      <p>No questionnaire provided</p>
    </template>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';
import { Prop } from 'vue-property-decorator';
import { Questionnaire, QuestionnaireResponse } from "fhir/r4b";

function loadScript(src: string) {
  return new Promise((resolve, reject) => {
    const tag = document.createElement('script');
    tag.setAttribute('src', src);
    tag.setAttribute('async', 'false');
    tag.setAttribute('defer', 'true');
    tag.addEventListener('error', reject);
    tag.addEventListener('load', resolve);
    document.body.appendChild(tag);
  });
}

let loaded: any = null;
let formData: QuestionnaireResponse | undefined = undefined;

@Component
export default class EditorAidboxFormsSection extends Vue {
  @Prop(Object) readonly questionnaire!: Questionnaire;

  questionnaireResponseString: string = '';

  async mounted() {
    if (!loaded) {
      loaded = await loadScript('https://form-builder.aidbox.app/static/aidbox-forms-renderer-webcomponent.js');
    }
  }

  /** Show this QR in the display (if it wasn't generated by itself) */
  async renderQuestionnaireResponse(response: QuestionnaireResponse, questionnaire: Questionnaire) {
    if (response.meta?.tag?.find(t => t.code?.startsWith('aidbox'))) {
      return;
    }
    const applyQr: QuestionnaireResponse = JSON.parse(JSON.stringify(response));
    delete applyQr.meta;
    applyQr.status = 'in-progress'; // as the Aidbox renderer will disable all controls in a `completed` state
    console.log("Rendering response in Aidbox renderer", response);
    this.questionnaireResponseString = JSON.stringify(applyQr);
    formData = applyQr;
  }

  handleChange(event: any) {
    const response = event.detail;
    formData = response;
    console.log("QuestionnaireResponse updated", response);
  }

  public logResponse() {
    console.log(formData);
    const response: QuestionnaireResponse = JSON.parse(JSON.stringify(formData));

    // ensure there is a tag for the aidbox renderer in place
    if (!response.meta?.tag?.find(t => t.code?.startsWith('aidbox'))) {
      if (!response.meta) response.meta = { tag: [] };
      if (!response.meta.tag) response.meta.tag = [];
      response.meta.tag!.push({ code: 'aidbox:generated' });
    }

    // remove the lforms tag if it was there.
    if (response.meta?.tag?.find(t => t.code?.startsWith('lforms'))) {
      response.meta.tag = response.meta.tag!.filter(t => !t.code?.startsWith('lforms'));
    }

    // remove the CSIRO tag if it was there.
    if (response.meta?.tag?.find(t => t.code?.startsWith('csiro'))) {
      response.meta.tag = response.meta.tag!.filter(t => !t.code?.startsWith('csiro'));
    }

    this.$emit("response", response);
  }
}
</script>